export const ASEGURADORAS = [
  { id: 1,  nombre: "GNP Seguros" },
  { id: 2,  nombre: "AXA Seguros" },
  { id: 3,  nombre: "MAPFRE" },
  { id: 4,  nombre: "MetLife" },
  { id: 5,  nombre: "Zurich" },
  { id: 6,  nombre: "Atlas" },
  { id: 7,  nombre: "BX+" },
  { id: 8,  nombre: "Cigna" },
  { id: 9,  nombre: "SURA" },
  { id: 10, nombre: "BBVA Seguros" },
  { id: 11, nombre: "Allianz" },
  { id: 12, nombre: "Monterrey NYL" },
  { id: 13, nombre: "Inbursa" },
  { id: 14, nombre: "Chubb" },
  { id: 15, nombre: "Quálitas" },
  { id: 16, nombre: "Otro" },
] as const
