export const ESPECIALIDADES_MEDICAS = [
  "Anestesiología",
  "Cardiología",
  "Cardiología Intervencionista",
  "Cirugía Cardiovascular",
  "Cirugía de Columna",
  "Cirugía General",
  "Cirugía Laparoscópica",
  "Cirugía Oncológica",
  "Cirugía Plástica y Reconstructiva",
  "Cirugía de Tórax",
  "Dermatología",
  "Endocrinología",
  "Gastroenterología",
  "Ginecología y Obstetricia",
  "Hematología",
  "Hepatología",
  "Infectología",
  "Mastología",
  "Medicina del Dolor",
  "Medicina Interna",
  "Nefrología",
  "Neurocirugía",
  "Neurología",
  "Neumología",
  "Oftalmología",
  "Oncología Médica",
  "Ortopedia y Traumatología",
  "Otorrinolaringología",
  "Pediatría",
  "Proctología",
  "Psiquiatría",
  "Radiología e Imagen",
  "Radioterapia",
  "Reumatología",
  "Urología",
] as const

export type EspecialidadMedica = (typeof ESPECIALIDADES_MEDICAS)[number]
